### ISSUE TITLE
README instructions may be out of date

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/login.dfe.directories#189]
I'm trying to get this app up and running locally but running into the following issues when following the instructions in the README file.

I've cloned the repo, run `npm i` and `npm run setup` with success but fail when trying to run `npm run dev`.

I made the following change to `config/login.dfe.directories.dev.json` in an attempt to simplify matters 

```diff
   },
   "adapter": {
-    "id": "9af9f8a2-ceec-461f-8db4-ff37073903df",
-    "type": "redis",
-    "params": {
-      "redisurl": "redis://127.0.0.1:6379/0"
-    }
+    "type": "file"
   },
```

The error I'm hitting is:

```bash
❯ npm run dev

> login.dfe.directories@0.0.1 dev /Users/peter/Projects/department-for-education/examples/login.dfe.directories
> PORT=4439 NODE_ENV=dev NODE_TLS_REJECT_UNAUTHORIZED=0 node src/index.js

/Users/peter/Projects/department-for-education/examples/login.dfe.directories/src/infrastructure/logger/index.js:40
if (config.hostingEnvironment.applicationInsights) {
           ^

TypeError: Cannot read property 'hostingEnvironment' of null
    at Object.<anonymous> (/Users/peter/Projects/department-for-education/examples/login.dfe.directories/src/infrastructure/logger/index.js:40:12)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/peter/Projects/department-for-education/examples/login.dfe.directories/src/index.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! login.dfe.directories@0.0.1 dev: `PORT=4439 NODE_ENV=dev NODE_TLS_REJECT_UNAUTHORIZED=0 node src/index.js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the login.dfe.directories@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peter/.npm/_logs/2019-03-29T11_14_05_518Z-debug.log
```

And the contents of the log file:

```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.5.0
3 info using node@v11.6.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle login.dfe.directories@0.0.1~predev: login.dfe.directories@0.0.1
6 info lifecycle login.dfe.directories@0.0.1~dev: login.dfe.directories@0.0.1
7 verbose lifecycle login.dfe.directories@0.0.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle login.dfe.directories@0.0.1~dev: PATH: <redacted>
9 verbose lifecycle login.dfe.directories@0.0.1~dev: CWD: /Users/peter/Projects/department-for-education/examples/login.dfe.directories
10 silly lifecycle login.dfe.directories@0.0.1~dev: Args: [ '-c',
10 silly lifecycle   'PORT=4439 NODE_ENV=dev NODE_TLS_REJECT_UNAUTHORIZED=0 node src/index.js ' ]
11 silly lifecycle login.dfe.directories@0.0.1~dev: Returned: code: 1  signal: null
12 info lifecycle login.dfe.directories@0.0.1~dev: Failed to exec dev script
13 verbose stack Error: login.dfe.directories@0.0.1 dev: `PORT=4439 NODE_ENV=dev NODE_TLS_REJECT_UNAUTHORIZED=0 node src/index.js `
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid login.dfe.directories@0.0.1
15 verbose cwd /Users/peter/Projects/department-for-education/examples/login.dfe.directories
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/Cellar/node/11.6.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v11.6.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error login.dfe.directories@0.0.1 dev: `PORT=4439 NODE_ENV=dev NODE_TLS_REJECT_UNAUTHORIZED=0 node src/index.js `
22 error Exit status 1
23 error Failed at the login.dfe.directories@0.0.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I assume I'm missing something somewhere, any pointers would be welcome!

**Comment by floydprice** [comment]
Noted... closing this for now but a new repo will be available soon with instructions on running the whole micro service formation
